# generated by datamodel-codegen:
#   filename:  derivative_info.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import definitions


class SettlementPrice(RootModel[float]):
    root: Annotated[float, Field(ge=0.0)]
    """
    清算値段（証拠金計算・損益計算の基準）
    """


class DerivativeInfo(BaseModel):
    """
    先物・オプション共通の情報を表現する
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    multiplier: float
    """
    契約乗数（1契約あたりの乗数）
    """
    tick_size: float
    """
    呼値単位（最小価格変動）
    """
    tick_value: float | None = None
    """
    ティック価値（1ティックあたりの金額変動）
    """
    contract_value: float | None = None
    """
    契約基本価値
    """
    contract_value_currency: definitions.Currency | None = None
    """
    契約価値の通貨
    """
    lot_size: float | None = None
    """
    取引単位（注文可能な最小数量単位）
    """
    min_order_size: float | None = None
    """
    最小注文数量
    """
    max_order_size: float | None = None
    """
    最大注文数量
    """
    underlying_symbol: definitions.Symbol
    """
    原資産のシンボル
    """
    underlying_type: definitions.UnderlyingType
    """
    原資産タイプ
    """
    is_perpetual: bool | None = None
    """
    無期限契約か否か（暗号資産デリバティブ向け）
    """
    is_inverse: bool | None = None
    """
    インバース契約か否か（false=linear、暗号資産デリバティブ向け）
    """
    settlement_method: definitions.SettlementMethod | None = None
    """
    決済方法
    """
    settlement_currency: definitions.Currency | None = None
    """
    決済通貨
    """
    settlement_price: SettlementPrice | None = None
    """
    清算値段（証拠金計算・損益計算の基準）
    """
