# generated by datamodel-codegen:
#   filename:  instrument.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import definitions


class Instrument(BaseModel):
    """
    銘柄識別情報を表現する
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    symbol: definitions.Symbol
    """
    銘柄識別子
    """
    asset_class: definitions.AssetClass
    """
    資産クラス
    """
    currency: definitions.Currency | None = None
    """
    単一通貨（株式・債券等）
    """
    exchange: definitions.Exchange | None = None
    """
    上場取引所（ISO 10383 MIC）
    """
    base_currency: definitions.Currency | None = None
    """
    基軸通貨（FX・暗号資産のペア商品）
    """
    quote_currency: definitions.Currency | None = None
    """
    決済通貨（FX・暗号資産のペア商品）
    """
