# generated by datamodel-codegen:
#   filename:  volume_info.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import definitions


class OpenInterest(RootModel[float]):
    root: Annotated[float, Field(ge=0.0)]
    """
    建玉残（未決済契約数）
    """


class VolumeInfo(BaseModel):
    """
    出来高と売買代金を表現する
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    symbol: definitions.Symbol
    """
    銘柄識別子
    """
    timestamp: definitions.Timestamp
    """
    データ取得時刻
    """
    volume: definitions.Size
    """
    出来高（数量ベース）
    """
    quote_volume: definitions.Size | None = None
    """
    売買代金（決済通貨建て）
    """
    open_interest: OpenInterest | None = None
    """
    建玉残（未決済契約数）
    """
