# generated by datamodel-codegen:
#   filename:  definitions.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class CommonTypeDefinitions(RootModel[Any]):
    root: Annotated[Any, Field(title="Common Type Definitions")]
    """
    マーケットデータスキーマの共通型定義
    """


class Timestamp(RootModel[AwareDatetime]):
    root: AwareDatetime
    """
    ISO 8601形式のタイムスタンプ (UTC)
    """


class Symbol(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]
    """
    銘柄識別子
    """


class Price(RootModel[float]):
    root: float
    """
    価格
    """


class Size(RootModel[float]):
    root: float
    """
    数量
    """


class Side(StrEnum):
    """
    売買方向
    """

    buy = "buy"
    sell = "sell"


class AssetClass(StrEnum):
    """
    資産クラス
    """

    equity = "equity"
    fund = "fund"
    bond = "bond"
    future = "future"
    option = "option"
    fx = "fx"
    crypto = "crypto"
    cfd = "cfd"


class Currency(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Z]{3}$")]
    """
    ISO 4217通貨コード（例: USD, JPY, EUR）
    """


class Exchange(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Z]{4}$")]
    """
    ISO 10383市場識別コード（例: XJPX, XNYS）
    """


class Date(RootModel[str]):
    root: Annotated[str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}$")]
    """
    日付（YYYY-MM-DD形式）
    """


class ExpirySeries(RootModel[str]):
    root: Annotated[str, Field(pattern="^\\d{4}(-\\d{2}|-W\\d{2}|-\\d{2}-\\d{2})$")]
    """
    満期系列識別子（YYYY-MM, YYYY-Www, YYYY-MM-DD形式）
    """


class OptionType(StrEnum):
    """
    オプションタイプ（コール/プット）
    """

    call = "call"
    put = "put"


class UnderlyingType(StrEnum):
    """
    原資産タイプ
    """

    stock = "stock"
    index_ = "index"
    etf = "etf"
    commodity = "commodity"
    currency = "currency"
    crypto = "crypto"


class ExerciseStyle(StrEnum):
    """
    オプション行使スタイル
    """

    american = "american"
    european = "european"
    bermudan = "bermudan"


class SettlementMethod(StrEnum):
    """
    決済方法
    """

    cash = "cash"
    physical = "physical"


class PriceLevel(BaseModel):
    """
    板情報の気配レベル
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    price: Price
    """
    気配値
    """
    size: Size
    """
    数量
    """
