# generated by datamodel-codegen:
#   filename:  expiry_info.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import definitions


class ExpiryInfo(BaseModel):
    """
    先物・オプションの満期関連情報を表現する
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    expiry: definitions.ExpirySeries | None = None
    """
    満期系列識別子（YYYY-MM, YYYY-Www, YYYY-MM-DD形式）
    """
    last_trading_day: definitions.Date | None = None
    """
    取引可能な最終日
    """
    expiration_date: definitions.Date
    """
    満期日/SQ日
    """
    settlement_date: definitions.Date | None = None
    """
    決済日
    """
