# generated by datamodel-codegen:
#   filename:  ohlcv.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import definitions


class OHLCV(BaseModel):
    """
    ローソク足データを表現する（始値、高値、安値、終値、出来高）
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    symbol: definitions.Symbol
    """
    銘柄識別子
    """
    timestamp: definitions.Timestamp
    """
    足の開始時刻
    """
    open: definitions.Price
    """
    始値
    """
    high: definitions.Price
    """
    高値
    """
    low: definitions.Price
    """
    安値
    """
    close: definitions.Price
    """
    終値
    """
    volume: definitions.Size
    """
    出来高
    """
    quote_volume: definitions.Size | None = None
    """
    売買代金（決済通貨建ての出来高）
    """
