# generated by datamodel-codegen:
#   filename:  option_info.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import definitions


class OptionInfo(BaseModel):
    """
    オプション固有の情報を表現する
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    strike_price: definitions.Price
    """
    権利行使価格
    """
    option_type: definitions.OptionType
    """
    オプションタイプ（call/put）
    """
    exercise_style: definitions.ExerciseStyle | None = None
    """
    行使スタイル（american/european/bermudan）
    """
