# generated by datamodel-codegen:
#   filename:  orderbook.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import definitions


class OrderBook(BaseModel):
    """
    複数レベルの板情報を表現する
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    symbol: definitions.Symbol
    """
    銘柄識別子
    """
    timestamp: definitions.Timestamp
    """
    板情報取得時刻
    """
    bids: list[definitions.PriceLevel]
    """
    買い板（価格降順）
    """
    asks: list[definitions.PriceLevel]
    """
    売り板（価格昇順）
    """
