# generated by datamodel-codegen:
#   filename:  quote.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import definitions


class Quote(BaseModel):
    """
    最良気配値（BBO: Best Bid/Offer）を表現する
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    symbol: definitions.Symbol
    """
    銘柄識別子
    """
    timestamp: definitions.Timestamp
    """
    気配値取得時刻
    """
    bid: definitions.Price
    """
    買い気配値
    """
    ask: definitions.Price
    """
    売り気配値
    """
    bid_size: definitions.Size | None = None
    """
    買い気配の数量
    """
    ask_size: definitions.Size | None = None
    """
    売り気配の数量
    """
