# generated by datamodel-codegen:
#   filename:  trade.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import definitions


class Trade(BaseModel):
    """
    個別約定（歩み値 / Time & Sales）を表現する
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    symbol: definitions.Symbol
    """
    銘柄識別子
    """
    timestamp: definitions.Timestamp
    """
    約定時刻
    """
    price: definitions.Price
    """
    約定価格
    """
    size: definitions.Size
    """
    約定数量
    """
    side: definitions.Side
    """
    売買方向（buy/sell）
    """
